CREATE DATABASE ds60 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER 'ds60'@'localhost' IDENTIFIED BY 'ds60';
GRANT ALL PRIVILEGES ON ds60.* TO 'ds60'@'localhost';
FLUSH PRIVILEGES;
